version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: quizmify-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: quizmify
      MYSQL_DATABASE: quizmify
      MYSQL_USER: quizmify
      MYSQL_PASSWORD: quizmify
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:latest
    container_name: quizmify-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data: 